version: '3'

services:
  price-calculation:
    image: railwaypricecalculation/price:0.1.0
    container_name: price
    privileged: true
    ports:
      - 8080:8080

  fare-calculation:
    image: railwaypricecalculation/fare:0.1.0
    container_name: fare
    privileged: true
    expose:
      - 8080

  super-express-surcharge-calculation:
    image: railwaypricecalculation/super-express-surcharge:0.1.0
    container_name: super-express-surcharge
    privileged: true
    expose:
      - 8080

  discount-calculation:
    image: railwaypricecalculation/discount:0.1.0
    container_name: discount
    privileged: true
    expose:
      - 8080

  catalogue:
    image: railwaypricecalculation/catalogue:0.1.0
    container_name: catalogue
    privileged: true
    expose:
      - 8080
    depends_on:
      - catalogue-db

  catalogue-db:
    image: postgres:latest
    container_name: catalogue-db
    privileged: true
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
      - 5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d

